import {
  AirVent,
  Archive,
  Armchair,
  Baby,
  Bath,
  Battery,
  BedDouble,
  BedSingle,
  BookOpen,
  Box,
  Briefcase,
  Brush,
  Car,
  Cat,
  ChefHat,
  Coffee,
  CookingPot,
  DoorOpen,
  Droplet,
  Droplets,
  Dumbbell,
  Fan,
  Flame,
  Flower2,
  Funnel,
  Gamepad2,
  GlassWater,
  Heater,
  House,
  LampFloor,
  Laptop,
  Leaf,
  Lightbulb,
  type LucideIcon,
  Package,
  Plug,
  Recycle,
  Refrigerator,
  Shield,
  Shirt,
  ShowerHead,
  Snowflake,
  Sofa,
  Sparkles,
  SprayCan,
  Sprout,
  Sun,
  SunSnow,
  Thermometer,
  Toilet,
  ToyBrick,
  Trash,
  Tv,
  Utensils,
  Warehouse,
  WashingMachine,
  WavesHorizontal,
  Wind,
  Zap,
} from "lucide-react";

// 位置與類別的 icon：資料庫存的 Lucide 名稱 → 元件。
// 涵蓋 placeIcons.ts 的兩份精選清單（共 60 個，重複的只列一次），名稱已確認存在於 lucide-react 1.45.0。
// 畫面上的操作 icon（返回、刪除等）直接 import lucide-react，不經過這裡。
const ICONS: Partial<Record<string, LucideIcon>> = {
  // 位置
  sofa: Sofa,
  armchair: Armchair,
  tv: Tv,
  "lamp-floor": LampFloor,
  utensils: Utensils,
  "cooking-pot": CookingPot,
  "chef-hat": ChefHat,
  refrigerator: Refrigerator,
  "bed-double": BedDouble,
  "bed-single": BedSingle,
  baby: Baby,
  "toy-brick": ToyBrick,
  "book-open": BookOpen,
  laptop: Laptop,
  briefcase: Briefcase,
  bath: Bath,
  "shower-head": ShowerHead,
  toilet: Toilet,
  "washing-machine": WashingMachine,
  shirt: Shirt,
  sun: Sun,
  "flower-2": Flower2,
  sprout: Sprout,
  car: Car,
  warehouse: Warehouse,
  "door-open": DoorOpen,
  house: House,
  dumbbell: Dumbbell,
  "gamepad-2": Gamepad2,
  cat: Cat,
  // 類別（washing-machine、shower-head 上面已有）
  "air-vent": AirVent,
  fan: Fan,
  wind: Wind,
  snowflake: Snowflake,
  "sun-snow": SunSnow,
  thermometer: Thermometer,
  heater: Heater,
  droplet: Droplet,
  droplets: Droplets,
  "glass-water": GlassWater,
  funnel: Funnel,
  package: Package,
  box: Box,
  archive: Archive,
  flame: Flame,
  battery: Battery,
  lightbulb: Lightbulb,
  plug: Plug,
  zap: Zap,
  "spray-can": SprayCan,
  sparkles: Sparkles,
  brush: Brush,
  trash: Trash,
  recycle: Recycle,
  leaf: Leaf,
  shield: Shield,
  "waves-horizontal": WavesHorizontal,
  coffee: Coffee,
};

type Props = {
  name: string;
  size?: number;
  strokeWidth?: number;
};

/** 原型的 ic() 預設是 size 20、線條粗細 1.75 */
function Icon({ name, size = 20, strokeWidth = 1.75 }: Props) {
  // 資料庫裡的名稱不在清單中時（例如手動改過）用 Package 代替，不讓整頁壞掉
  const Component = ICONS[name] ?? Package;
  return <Component size={size} strokeWidth={strokeWidth} aria-hidden />;
}

export default Icon;
