// 位置與類別可以選的 icon 精選清單（P2-11，PRODUCT.md §4.6），照 docs/prototype/p0.html 的 ROOM_ICONS、CAT_ICONS。
// 資料庫存的就是這些 Lucide 名稱。60 個名稱都已確認存在於 lucide-react 1.45.0（P2-11 逐一比對檔案）。
// 新增名稱時，Icon.tsx 的對應表要一起加，否則會顯示成預設的包裹圖示。

export const LOCATION_ICONS = [
  "sofa",
  "armchair",
  "tv",
  "lamp-floor",
  "utensils",
  "cooking-pot",
  "chef-hat",
  "refrigerator",
  "bed-double",
  "bed-single",
  "baby",
  "toy-brick",
  "book-open",
  "laptop",
  "briefcase",
  "bath",
  "shower-head",
  "toilet",
  "washing-machine",
  "shirt",
  "sun",
  "flower-2",
  "sprout",
  "car",
  "warehouse",
  "door-open",
  "house",
  "dumbbell",
  "gamepad-2",
  "cat",
] as const;

export const CATEGORY_ICONS = [
  "air-vent",
  "fan",
  "wind",
  "snowflake",
  "sun-snow",
  "thermometer",
  "heater",
  "droplet",
  "droplets",
  "glass-water",
  "funnel",
  "package",
  "box",
  "archive",
  "flame",
  "washing-machine",
  "shower-head",
  "battery",
  "lightbulb",
  "plug",
  "zap",
  "spray-can",
  "sparkles",
  "brush",
  "trash",
  "recycle",
  "leaf",
  "shield",
  "waves-horizontal",
  "coffee",
] as const;
